export const BADGES_CONFIG = {
  // === ACHIEVEMENTS ===
  FIRST_WORKOUT: {
    id: 'FIRST_WORKOUT',
    name: 'First Sweat',
    icon: '🏃',
    color: '#3b82f6',
    bg: 'rgba(59,130,246,0.12)',
    description: 'Logged your very first workout',
    rarity: 'common',
    category: 'achievement',
    trigger: '1 workout',
  },
  CENTURY_SWEAT: {
    id: 'CENTURY_SWEAT',
    name: 'Century Sweat',
    icon: '🔥',
    color: '#f97316',
    bg: 'rgba(249,115,22,0.12)',
    description: 'Earned 100 sweat credits',
    rarity: 'common',
    category: 'achievement',
    trigger: '100 sv',
  },
  CREDITS_500: {
    id: 'CREDITS_500',
    name: 'Power Earner',
    icon: '💰',
    color: '#eab308',
    bg: 'rgba(234,179,8,0.12)',
    description: 'Earned 500 sweat credits',
    rarity: 'uncommon',
    category: 'achievement',
    trigger: '500 sv',
  },
  CREDITS_1000: {
    id: 'CREDITS_1000',
    name: 'Sweat Elite',
    icon: '💎',
    color: '#8b5cf6',
    bg: 'rgba(139,92,246,0.12)',
    description: 'Earned 1,000 sweat credits',
    rarity: 'rare',
    category: 'achievement',
    trigger: '1,000 sv',
  },
  WORKOUT_10: {
    id: 'WORKOUT_10',
    name: 'Getting Serious',
    icon: '💪',
    color: '#10b981',
    bg: 'rgba(16,185,129,0.12)',
    description: 'Completed 10 workouts',
    rarity: 'common',
    category: 'achievement',
    trigger: '10 workouts',
  },
  WORKOUT_50: {
    id: 'WORKOUT_50',
    name: 'Endurance Master',
    icon: '🏅',
    color: '#c0a24a',
    bg: 'rgba(192,162,74,0.12)',
    description: 'Completed 50 workouts',
    rarity: 'rare',
    category: 'achievement',
    trigger: '50 workouts',
  },
  MARATHON_MODE: {
    id: 'MARATHON_MODE',
    name: 'Marathon Mode',
    icon: '🗺️',
    color: '#a855f7',
    bg: 'rgba(168,85,247,0.12)',
    description: 'Covered 100 km total distance',
    rarity: 'uncommon',
    category: 'achievement',
    trigger: '100 km total',
  },
  CALORIE_CRUSHER: {
    id: 'CALORIE_CRUSHER',
    name: 'Calorie Crusher',
    icon: '⚡',
    color: '#ef4444',
    bg: 'rgba(239,68,68,0.12)',
    description: 'Burned 10,000 calories total',
    rarity: 'epic',
    category: 'achievement',
    trigger: '10,000 cal',
  },

  // === STREAKS ===
  ON_FIRE: {
    id: 'ON_FIRE',
    name: 'On Fire',
    icon: '🔥',
    color: '#f97316',
    bg: 'rgba(249,115,22,0.12)',
    description: 'Maintained a 3-day workout streak',
    rarity: 'common',
    category: 'streak',
    trigger: '3-day streak',
  },
  RED_HOT: {
    id: 'RED_HOT',
    name: 'Red Hot',
    icon: '🌡️',
    color: '#ef4444',
    bg: 'rgba(239,68,68,0.12)',
    description: 'Maintained a 7-day workout streak',
    rarity: 'uncommon',
    category: 'streak',
    trigger: '7-day streak',
  },
  UNSTOPPABLE: {
    id: 'UNSTOPPABLE',
    name: 'Unstoppable',
    icon: '⚡',
    color: '#eab308',
    bg: 'rgba(234,179,8,0.12)',
    description: 'Maintained a 14-day workout streak',
    rarity: 'rare',
    category: 'streak',
    trigger: '14-day streak',
  },
  LEGENDARY: {
    id: 'LEGENDARY',
    name: 'Legendary',
    icon: '👑',
    color: '#d97706',
    bg: 'rgba(217,119,6,0.12)',
    description: 'Maintained a 30-day workout streak',
    rarity: 'epic',
    category: 'streak',
    trigger: '30-day streak',
  },

  // === ACTIVITY TYPES ===
  RUNNERS_HIGH: {
    id: 'RUNNERS_HIGH',
    name: "Runner's High",
    icon: '🏃',
    color: '#3b82f6',
    bg: 'rgba(59,130,246,0.12)',
    description: 'Completed 20 running sessions',
    rarity: 'uncommon',
    category: 'activity',
    trigger: '20 runs',
  },
  CYCLISTS_PARADISE: {
    id: 'CYCLISTS_PARADISE',
    name: "Cyclist's Paradise",
    icon: '🚴',
    color: '#10b981',
    bg: 'rgba(16,185,129,0.12)',
    description: 'Completed 20 cycling sessions',
    rarity: 'uncommon',
    category: 'activity',
    trigger: '20 rides',
  },
  IRON_LIFTER: {
    id: 'IRON_LIFTER',
    name: 'Iron Lifter',
    icon: '🏋️',
    color: '#ef4444',
    bg: 'rgba(239,68,68,0.12)',
    description: 'Completed 20 strength sessions',
    rarity: 'uncommon',
    category: 'activity',
    trigger: '20 sessions',
  },
  WATER_CHILD: {
    id: 'WATER_CHILD',
    name: 'Water Child',
    icon: '🏊',
    color: '#0ea5e9',
    bg: 'rgba(14,165,233,0.12)',
    description: 'Completed 20 swimming sessions',
    rarity: 'uncommon',
    category: 'activity',
    trigger: '20 swims',
  },
  ALLROUNDER: {
    id: 'ALLROUNDER',
    name: 'Allrounder',
    icon: '🎯',
    color: '#a855f7',
    bg: 'rgba(168,85,247,0.12)',
    description: 'Completed 5+ sessions of every activity type',
    rarity: 'epic',
    category: 'activity',
    trigger: '5 of each',
  },

  // === SOCIAL ===
  FIRST_FRIEND: {
    id: 'FIRST_FRIEND',
    name: 'First Friend',
    icon: '👋',
    color: '#ec4899',
    bg: 'rgba(236,72,153,0.12)',
    description: 'Added your first training partner',
    rarity: 'common',
    category: 'social',
    trigger: '1 friend',
  },
  SQUAD_GOALS: {
    id: 'SQUAD_GOALS',
    name: 'Squad Goals',
    icon: '👥',
    color: '#ec4899',
    bg: 'rgba(236,72,153,0.12)',
    description: 'Built a squad of 5 training partners',
    rarity: 'uncommon',
    category: 'social',
    trigger: '5 friends',
  },
  FRIEND_MAGNET: {
    id: 'FRIEND_MAGNET',
    name: 'Friend Magnet',
    icon: '🧲',
    color: '#db2777',
    bg: 'rgba(219,39,119,0.12)',
    description: 'Connected with 10 training partners',
    rarity: 'rare',
    category: 'social',
    trigger: '10 friends',
  },

  // === EXPLORER ===
  GOAL_GETTER: {
    id: 'GOAL_GETTER',
    name: 'Goal Getter',
    icon: '🎯',
    color: '#10b981',
    bg: 'rgba(16,185,129,0.12)',
    description: 'Completed your first training goal',
    rarity: 'common',
    category: 'explorer',
    trigger: '1 goal done',
  },
  GOAL_CRUSHER: {
    id: 'GOAL_CRUSHER',
    name: 'Goal Crusher',
    icon: '🏆',
    color: '#d97706',
    bg: 'rgba(217,119,6,0.12)',
    description: 'Crushed 5 training goals',
    rarity: 'uncommon',
    category: 'explorer',
    trigger: '5 goals done',
  },
  GARMIN_CONNECTED: {
    id: 'GARMIN_CONNECTED',
    name: 'Verified Athlete',
    icon: '⌚',
    color: '#3b82f6',
    bg: 'rgba(59,130,246,0.12)',
    description: 'Connected your Garmin device',
    rarity: 'common',
    category: 'explorer',
    trigger: 'Garmin sync',
  },
  INSIGHT_SEEKER: {
    id: 'INSIGHT_SEEKER',
    name: 'Insight Seeker',
    icon: '📈',
    color: '#a855f7',
    bg: 'rgba(168,85,247,0.12)',
    description: 'Analyzed your training insights',
    rarity: 'common',
    category: 'explorer',
    trigger: 'View insights',
  },
  LEADERBOARD_PIONEER: {
    id: 'LEADERBOARD_PIONEER',
    name: 'Leaderboard Pioneer',
    icon: '📊',
    color: '#3b82f6',
    bg: 'rgba(59,130,246,0.12)',
    description: 'Checked the global leaderboard',
    rarity: 'common',
    category: 'explorer',
    trigger: 'View rankings',
  },
};

export const BADGE_CATEGORIES = [
  { id: 'achievement', label: 'Achievements', description: 'Fitness milestones' },
  { id: 'streak',      label: 'Streaks',      description: 'Consistency rewards' },
  { id: 'activity',    label: 'Activities',   description: 'Sport variety' },
  { id: 'social',      label: 'Social',       description: 'Training community' },
  { id: 'explorer',    label: 'Explorer',     description: 'First steps' },
];

export const RARITY_CONFIG = {
  common:   { label: 'Common',   color: '#6b7280', bg: 'rgba(107,114,128,0.10)' },
  uncommon: { label: 'Uncommon', color: '#3b82f6', bg: 'rgba(59,130,246,0.10)'  },
  rare:     { label: 'Rare',     color: '#a855f7', bg: 'rgba(168,85,247,0.10)'  },
  epic:     { label: 'Epic',     color: '#d97706', bg: 'rgba(217,119,6,0.10)'   },
};
