/**
 * Demo provider data — hardcoded realistic training scenarios for QA and preview.
 * Always labeled "Demo Mode" in UI. No real user data.
 */

export const DEMO_PROFILE = {
  userId: 'demo-user',
  trainingPhilosophy: 'cns_first',
  primaryGoal: 'Hypertrophy with CNS protection — build muscle without accumulating fatigue debt',
  trainingBackground: '10 years hybrid training. Strength + triathlon. No major injuries.',
  currentChallenges: 'HRV tanking after heavy CNS weeks. Inconsistent sleep schedule from work travel.',
  riskTolerance: 'medium',
};

export const DEMO_SCENARIOS = [
  {
    id: 'green_day',
    label: 'Green Day',
    description: 'All signals healthy — should recommend Train',
    dailyHealth: {
      date: '2026-05-18',
      sleepDurationMin: 450,
      sleepScore: 82,
      hrvMs: 72,
      restingHrBpm: 46,
      restingHrBaseline: 48,
      hrvBaselineLow: 58,
      bodyBatteryStart: 88,
      trainingReadiness: 85,
      stressAvg: 22,
      subjectiveEnergy: 8,
      subjectiveSoreness: 2,
      subjectiveStress: 2,
    },
    subjective: { illnessSymptoms: false, injuryPain: false },
  },
  {
    id: 'low_hrv_rhr',
    label: 'HRV + RHR Flags',
    description: 'Both RHR elevated and HRV suppressed — should recommend Recover',
    dailyHealth: {
      date: '2026-05-18',
      sleepDurationMin: 390,
      sleepScore: 61,
      hrvMs: 44,
      restingHrBpm: 58,
      restingHrBaseline: 48,
      hrvBaselineLow: 58,
      bodyBatteryStart: 42,
      trainingReadiness: 48,
      stressAvg: 55,
      subjectiveEnergy: 4,
      subjectiveSoreness: 5,
      subjectiveStress: 5,
    },
    subjective: { illnessSymptoms: false, injuryPain: false },
  },
  {
    id: 'poor_sleep',
    label: 'Poor Sleep',
    description: 'Sleep < 5 hours — hard Rest override',
    dailyHealth: {
      date: '2026-05-18',
      sleepDurationMin: 270,
      sleepScore: 40,
      hrvMs: 55,
      restingHrBpm: 52,
      restingHrBaseline: 48,
      hrvBaselineLow: 58,
      bodyBatteryStart: 25,
      trainingReadiness: 30,
      stressAvg: 70,
      subjectiveEnergy: 3,
      subjectiveSoreness: 3,
      subjectiveStress: 7,
    },
    subjective: { illnessSymptoms: false, injuryPain: false },
  },
  {
    id: 'illness',
    label: 'Illness Symptoms',
    description: 'Illness flag present — hard Rest override',
    dailyHealth: {
      date: '2026-05-18',
      sleepDurationMin: 420,
      sleepScore: 65,
      trainingReadiness: 55,
      subjectiveEnergy: 3,
    },
    subjective: { illnessSymptoms: true, injuryPain: false },
  },
  {
    id: 'limited_sleep',
    label: 'Limited Sleep',
    description: '5-6.5 hrs sleep, readiness OK — philosophy bias for limited_sleep',
    dailyHealth: {
      date: '2026-05-18',
      sleepDurationMin: 340,
      sleepScore: 58,
      hrvMs: 62,
      restingHrBpm: 50,
      restingHrBaseline: 48,
      hrvBaselineLow: 58,
      bodyBatteryStart: 55,
      trainingReadiness: 60,
      stressAvg: 40,
      subjectiveEnergy: 5,
      subjectiveSoreness: 3,
      subjectiveStress: 4,
    },
    subjective: { illnessSymptoms: false, injuryPain: false },
  },
];

export const DEMO_SESSIONS = [
  {
    id: 'demo-session-1',
    date: '2026-05-18',
    sportType: 'strength',
    durationSec: 3600,
    trainingLoad: 85,
    anaerobicTe: 2.8,
    maxHrBpm: 162,
    avgHrBpm: 128,
  },
  {
    id: 'demo-session-2',
    date: '2026-05-17',
    sportType: 'bike',
    durationSec: 5400,
    distanceM: 45000,
    trainingLoad: 72,
    aerobicTe: 3.2,
    avgHrBpm: 138,
    maxHrBpm: 155,
    z2RangeMin: 120,
    z2RangeMax: 126,
    timeInZ2Sec: 3200,
  },
];
